<a href="https://colab.research.google.com/github/joluva/datascience/blob/main/API2_Vasquez_Jorge_luis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***API-2 Vasquez Jorge Luis***

In [ ]:
# importamos las librerias de analisis Pandas y Numpy
import pandas as pd
import numpy as np

In [ ]:
# importamos los archivos para depurar y analizar
# poblacion.csv - empleo.csv - esperanza_de_vida.csv - exportaciones.csv - hogares_vivienda_superficie.csv

# armo los data frame de cada archivo
poblacion = pd.read_csv('poblacion.csv', encoding='latin-1')

hogares_vivienda_superficie = pd.read_csv('hogares_viviendas_superficie.csv', encoding='latin-1')

In [ ]:
# creo una funcion para ir analizando las primeras cinco lineas de cada data frame
def primeras_ultimas_cinco_filas(lista_df):
  for nombre, df in lista_df.items():
    #print(f"DataFrame {i+1}: ", i)
    print(f"Procesando Data Frame:  {nombre}")
    print(f"Primeras cinco lineas")
    print("-" * 50)      # armo un separador visual entre cada DF
    print(df.head())     # muestro las primeras 5 lineas del data frame
    print("-" * 50)      # armo un separador visual entre cada DF
    print(f"Ultimas cinco lineas\n")
    print(df.tail())     # muestro las ultimas cinco filas del archivo
    print("_" * 50)      # armo un separador visual entre cada df
    print(f"\nCantidad de filas y columnas: ",df.shape)      # muestro la cantidad de filas y columnas del DF
    print(f"\nTipos de datos del archivo:\n ")
    print(df.dtypes)     # muestro los tipos de datos del DF
    print(f"\nPrincipales estadisticas descriptivas:\n")
    print(df.describe()) # visualizamos la estadistica del DF
    print("-" * 50)      # armo un separador visul entre cada DF

In [ ]:
# creo un diccionario con los nombres de los data frame
dataframe_dict = {
    'poblacion': poblacion,
    'hogares_vivienda_superficie': hogares_vivienda_superficie
}

# llamo a la funcion que muestra las primeras cinco filas
primeras_ultimas_cinco_filas(dataframe_dict)

Procesando Data Frame:  poblacion
Primeras cinco lineas
--------------------------------------------------
    provincia  anio  poblacion_total  poblacion_varones  poblacion_mujeres
0  Total País  2010         40788453           19940704           20847749
1  Total País  2011         41261490           20180791           21080699
2  Total País  2012         41733271           20420391           21312880
3  Total País  2013         42202935           20659037           21543898
4  Total País  2014         42669500           20896203           21773297
--------------------------------------------------
Ultimas cinco lineas

            provincia  anio  poblacion_total  poblacion_varones  \
770  Tierra del Fuego  2036           241593             122567
771  Tierra del Fuego  2037           245734             124625
772  Tierra del Fuego  2038           249853             126670
773  Tierra del Fuego  2039           253948             128702
774  Tierra del Fuego  2040           258020             130721

     poblacion_mujeres
770             119026
771             121109
772             123183
773             125246
774             127299
__________________________________________________

Cantidad de filas y columnas:  (775, 5)

Tipos de datos del archivo:

provincia            object
anio                  int64
poblacion_total       int64
poblacion_varones     int64
poblacion_mujeres     int64
dtype: object

Principales estadisticas descriptivas:

              anio  poblacion_total  poblacion_varones  poblacion_mujeres
count   775.000000     7.750000e+02       7.750000e+02       7.750000e+02
mean   2025.000000     3.777746e+06       1.856888e+06       1.920858e+06
std       8.950048     9.560571e+06       4.699604e+06       4.861043e+06
min    2010.000000     1.316610e+05       6.723500e+04       6.442600e+04
25%    2017.000000     5.845510e+05       2.906740e+05       2.934905e+05
50%    2025.000000     1.017731e+06       5.061010e+05       5.161370e+05
75%    2033.000000     1.855285e+06       9.138865e+05       9.404745e+05
max    2040.000000     5.277848e+07       2.603809e+07       2.674038e+07
--------------------------------------------------
Procesando Data Frame:  hogares_vivienda_superficie
Primeras cinco lineas
--------------------------------------------------
   provincia_id        provincia  hogares  viviendas_particulares  \
0             2  Capital Federal  1150134                 1423973
1             6     Buenos Aires  4789484                 5377786
2            10        Catamarca    96001                  113634
3            14          Córdoba  1031843                 1232211
4            18       Corrientes   267797                  292644

   viviendas_particulares_habitadas  superficie_km2
0                           1082998             200
1                           4425193          307571
2                             89376          102602
3                            978553          165321
4                            248844           88199
--------------------------------------------------
Ultimas cinco lineas

    provincia_id            provincia  hogares  viviendas_particulares  \
19            78           Santa Cruz    81796                   93881
20            82             Santa Fe  1023777                 1143651
21            86  Santiago del Estero   218025                  242034
22            90              Tucumán   368538                  396040
23            94     Tierra del Fuego    38956                   43360

    viviendas_particulares_habitadas  superficie_km2
19                             76233          243943
20                            948369          133007
21                            197906          136351
22                            335821           22524
23                             36689         1002445
__________________________________________________

Cantidad de filas y columnas:  (24, 6)

Tipos de datos del archivo:

provincia_id                         int64
provincia                           object
hogares                              int64
viviendas_particulares               int64
viviendas_particulares_habitadas     int64
superficie_km2                       int64
dtype: object

Principales estadisticas descriptivas:

       provincia_id       hogares  viviendas_particulares  \
count     24.000000  2.400000e+01            2.400000e+01
mean      48.000000  5.071531e+05            5.755052e+05
std       28.284271  9.631395e+05            1.087472e+06
min        2.000000  3.895600e+04            4.336000e+04
25%       25.000000  1.369578e+05            1.513558e+05
50%       48.000000  2.086070e+05            2.393215e+05
75%       71.000000  3.701838e+05            4.034278e+05
max       94.000000  4.789484e+06            5.377786e+06

       viviendas_particulares_habitadas  superficie_km2
count                      2.400000e+01    2.400000e+01
mean                       4.715628e+05    1.567198e+05
std                        8.908855e+05    1.940901e+05
min                        3.668900e+04    2.000000e+02
25%                        1.270420e+05    7.827275e+04
50%                        1.942515e+05    1.011175e+05
75%                        3.411782e+05    1.579462e+05
max                        4.425193e+06    1.002445e+06
--------------------------------------------------

In [ ]:
# filto el archivo de poblacion, elimino de la variable provincia el 'Total Pais'
poblacion_filtrado = poblacion[poblacion['provincia'] != 'Total País']
poblacion_filtrado

,provincia,anio,poblacion_total,poblacion_varones,poblacion_mujeres
31,Capital Federal,2010,3028481,1405566,1622915
32,Capital Federal,2011,3033639,1409835,1623804
33,Capital Federal,2012,3038860,1414105,1624755
34,Capital Federal,2013,3044076,1418339,1625737
35,Capital Federal,2014,3049229,1422507,1626722
...,...,...,...,...,...
770,Tierra del Fuego,2036,241593,122567,119026
771,Tierra del Fuego,2037,245734,124625,121109
772,Tierra del Fuego,2038,249853,126670,123183
773,Tierra del Fuego,2039,253948,128702,125246
774,Tierra del Fuego,2040,258020,130721,127299

In [ ]:
# usamos la funcion merge para combinar las tablas poblacion_filtrado con hogares en un nuevo dataframe, que llamaremos
# poblacion_superficie, la combinacion se hace donde los valores de la columna provincia coincida en ambos dataframe
poblacion_superficie = pd.merge(poblacion_filtrado, hogares_vivienda_superficie, left_on=['provincia'], right_on=['provincia'], how='left') #how left union por izquierda
poblacion_superficie

,provincia,anio,poblacion_total,poblacion_varones,poblacion_mujeres,provincia_id,hogares,viviendas_particulares,viviendas_particulares_habitadas,superficie_km2
0,Capital Federal,2010,3028481,1405566,1622915,2,1150134,1423973,1082998,200
1,Capital Federal,2011,3033639,1409835,1623804,2,1150134,1423973,1082998,200
2,Capital Federal,2012,3038860,1414105,1624755,2,1150134,1423973,1082998,200
3,Capital Federal,2013,3044076,1418339,1625737,2,1150134,1423973,1082998,200
4,Capital Federal,2014,3049229,1422507,1626722,2,1150134,1423973,1082998,200
...,...,...,...,...,...,...,...,...,...,...
739,Tierra del Fuego,2036,241593,122567,119026,94,38956,43360,36689,1002445
740,Tierra del Fuego,2037,245734,124625,121109,94,38956,43360,36689,1002445
741,Tierra del Fuego,2038,249853,126670,123183,94,38956,43360,36689,1002445
742,Tierra del Fuego,2039,253948,128702,125246,94,38956,43360,36689,1002445
743,Tierra del Fuego,2040,258020,130721,127299,94,38956,43360,36689,1002445

In [ ]:
# calcular un nuevo campo de dencidad de poblacion
poblacion_superficie['densidad_poblacional'] = poblacion_superficie['poblacion_total'] / poblacion_superficie['superficie_km2']
poblacion_superficie

,provincia,anio,poblacion_total,poblacion_varones,poblacion_mujeres,provincia_id,hogares,viviendas_particulares,viviendas_particulares_habitadas,superficie_km2,densidad_poblacional
0,Capital Federal,2010,3028481,1405566,1622915,2,1150134,1423973,1082998,200,15142.405000
1,Capital Federal,2011,3033639,1409835,1623804,2,1150134,1423973,1082998,200,15168.195000
2,Capital Federal,2012,3038860,1414105,1624755,2,1150134,1423973,1082998,200,15194.300000
3,Capital Federal,2013,3044076,1418339,1625737,2,1150134,1423973,1082998,200,15220.380000
4,Capital Federal,2014,3049229,1422507,1626722,2,1150134,1423973,1082998,200,15246.145000
...,...,...,...,...,...,...,...,...,...,...,...
739,Tierra del Fuego,2036,241593,122567,119026,94,38956,43360,36689,1002445,0.241004
740,Tierra del Fuego,2037,245734,124625,121109,94,38956,43360,36689,1002445,0.245135
741,Tierra del Fuego,2038,249853,126670,123183,94,38956,43360,36689,1002445,0.249244
742,Tierra del Fuego,2039,253948,128702,125246,94,38956,43360,36689,1002445,0.253329
743,Tierra del Fuego,2040,258020,130721,127299,94,38956,43360,36689,1002445,0.257391

In [ ]:
# comprobamos que no haya datos nulos
poblacion_superficie.isnull().sum()

provincia                           0
anio                                0
poblacion_total                     0
poblacion_varones                   0
poblacion_mujeres                   0
provincia_id                        0
hogares                             0
viviendas_particulares              0
viviendas_particulares_habitadas    0
superficie_km2                      0
densidad_poblacional                0
dtype: int64

Creo columna (fuera_de_rango), que toma del dataframe poblacion_superficie datos de la columna 'densidad_poblacional', le resta la media (promedio) de todos los valores de densidad_de_poblacion, uso np.mean y lo divido por la desviación standard calculada aplicando np.std a densidad_poblacional. Esto standariza los valores, y los convierte en una medida llamada z-core, este valor indica cuantas medidas están por encima o por debajo de la media.

In [ ]:
# hago el calculo de los valores que estan por encima o debajo de la media
poblacion_superficie['fuera_de_rango'] = (poblacion_superficie['densidad_poblacional'] - np.mean(poblacion_superficie['densidad_poblacional'])) / np.std(poblacion_superficie['densidad_poblacional'])
poblacion_superficie

,provincia,anio,poblacion_total,poblacion_varones,poblacion_mujeres,provincia_id,hogares,viviendas_particulares,viviendas_particulares_habitadas,superficie_km2,densidad_poblacional,fuera_de_rango
0,Capital Federal,2010,3028481,1405566,1622915,2,1150134,1423973,1082998,200,15142.405000,4.731966
1,Capital Federal,2011,3033639,1409835,1623804,2,1150134,1423973,1082998,200,15168.195000,4.740389
2,Capital Federal,2012,3038860,1414105,1624755,2,1150134,1423973,1082998,200,15194.300000,4.748916
3,Capital Federal,2013,3044076,1418339,1625737,2,1150134,1423973,1082998,200,15220.380000,4.757434
4,Capital Federal,2014,3049229,1422507,1626722,2,1150134,1423973,1082998,200,15246.145000,4.765849
...,...,...,...,...,...,...,...,...,...,...,...,...
739,Tierra del Fuego,2036,241593,122567,119026,94,38956,43360,36689,1002445,0.241004,-0.213774
740,Tierra del Fuego,2037,245734,124625,121109,94,38956,43360,36689,1002445,0.245135,-0.213773
741,Tierra del Fuego,2038,249853,126670,123183,94,38956,43360,36689,1002445,0.249244,-0.213771
742,Tierra del Fuego,2039,253948,128702,125246,94,38956,43360,36689,1002445,0.253329,-0.213770
743,Tierra del Fuego,2040,258020,130721,127299,94,38956,43360,36689,1002445,0.257391,-0.213769

In [ ]:
# aplicamos la funcion describe sobre el nuevo campo calculado fuera_de_rango
poblacion_superficie['fuera_de_rango'].describe()

count    7.440000e+02
mean     1.910061e-17
std      1.000673e+00
min     -2.138097e-01
25%     -2.124074e-01
50%     -2.107803e-01
75%     -2.072147e-01
max      4.828242e+00
Name: fuera_de_rango, dtype: float64

Calcular percentil de la columna densidad de poblacion
El percentil 99 es el valor por debajo del cual se encuentra el 99% de los datos. Es decir que solo el 1% de los datos son mayores a este valor

In [ ]:
# hago el calculo del percentil
p99 = np.percentile(poblacion_superficie['fuera_de_rango'], 99)
print(f"Calculo del percentil 99: ", p99)

Calculo del percentil 99:  4.821306724666532

In [ ]:
# muestro los registros mayores o iguales a p99
poblacion_superficie[poblacion_superficie['fuera_de_rango'] >= p99]

,provincia,anio,poblacion_total,poblacion_varones,poblacion_mujeres,provincia_id,hogares,viviendas_particulares,viviendas_particulares_habitadas,superficie_km2,densidad_poblacional,fuera_de_rango
13,Capital Federal,2023,3083770,1452588,1631182,2,1150134,1423973,1082998,200,15418.850,4.822258
14,Capital Federal,2024,3085483,1454716,1630767,2,1150134,1423973,1082998,200,15427.415,4.825056
15,Capital Federal,2025,3086680,1456560,1630120,2,1150134,1423973,1082998,200,15433.400,4.827011
16,Capital Federal,2026,3087338,1458111,1629227,2,1150134,1423973,1082998,200,15436.690,4.828085
17,Capital Federal,2027,3087434,1459359,1628075,2,1150134,1423973,1082998,200,15437.170,4.828242
18,Capital Federal,2028,3086973,1460309,1626664,2,1150134,1423973,1082998,200,15434.865,4.827489
19,Capital Federal,2029,3085971,1460970,1625001,2,1150134,1423973,1082998,200,15429.855,4.825853
20,Capital Federal,2030,3084450,1461355,1623095,2,1150134,1423973,1082998,200,15422.250,4.823369

**INFORME DE VALORES EXTREMOS SOBRE DENSIDAD DE POBLACION**


*   La densidad poblacional de Tierra del fuego es muy baja
*   Esta provincia esta por debajo del percentil 99 calculado

Analizamos la variable superficie_km2 de la tabla poblacion_superficie

In [ ]:
# busco la media en dentro de la variable superficie_km2 usando np.mean y generado una nueva variable rango_medio_km2
poblacion_superficie['rango_medio_km2'] = np.mean(poblacion_superficie['superficie_km2'])
poblacion_superficie

,provincia,anio,poblacion_total,poblacion_varones,poblacion_mujeres,provincia_id,hogares,viviendas_particulares,viviendas_particulares_habitadas,superficie_km2,densidad_poblacional,fuera_de_rango,rango_medio_km2
0,Capital Federal,2010,3028481,1405566,1622915,2,1150134,1423973,1082998,200,15142.405000,4.731966,156719.75
1,Capital Federal,2011,3033639,1409835,1623804,2,1150134,1423973,1082998,200,15168.195000,4.740389,156719.75
2,Capital Federal,2012,3038860,1414105,1624755,2,1150134,1423973,1082998,200,15194.300000,4.748916,156719.75
3,Capital Federal,2013,3044076,1418339,1625737,2,1150134,1423973,1082998,200,15220.380000,4.757434,156719.75
4,Capital Federal,2014,3049229,1422507,1626722,2,1150134,1423973,1082998,200,15246.145000,4.765849,156719.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,Tierra del Fuego,2036,241593,122567,119026,94,38956,43360,36689,1002445,0.241004,-0.213774,156719.75
740,Tierra del Fuego,2037,245734,124625,121109,94,38956,43360,36689,1002445,0.245135,-0.213773,156719.75
741,Tierra del Fuego,2038,249853,126670,123183,94,38956,43360,36689,1002445,0.249244,-0.213771,156719.75
742,Tierra del Fuego,2039,253948,128702,125246,94,38956,43360,36689,1002445,0.253329,-0.213770,156719.75
743,Tierra del Fuego,2040,258020,130721,127299,94,38956,43360,36689,1002445,0.257391,-0.213769,156719.75

In [ ]:
# aplico la funcion describe sobre la variable rango_medio_km2
poblacion_superficie['superficie_km2'].describe()

count    7.440000e+02
mean     1.567198e+05
std      1.901313e+05
min      2.000000e+02
25%      7.827275e+04
50%      1.011175e+05
75%      1.579462e+05
max      1.002445e+06
Name: superficie_km2, dtype: float64

In [ ]:
# hago el calculo del percentil 99 sobre rango_medio_km2
p99_rango_medio_km2 = np.percentile(poblacion_superficie['superficie_km2'], 99)
print(f"Calculo del percentil 99: ", p99_rango_medio_km2)

Calculo del percentil 99:  1002445.0

In [ ]:
# busco los registros mayores o iguales a p99_rago_medio_km2
poblacion_superficie[poblacion_superficie['superficie_km2'] >= p99]

,provincia,anio,poblacion_total,poblacion_varones,poblacion_mujeres,provincia_id,hogares,viviendas_particulares,viviendas_particulares_habitadas,superficie_km2,densidad_poblacional,fuera_de_rango,rango_medio_km2
0,Capital Federal,2010,3028481,1405566,1622915,2,1150134,1423973,1082998,200,15142.405000,4.731966,156719.75
1,Capital Federal,2011,3033639,1409835,1623804,2,1150134,1423973,1082998,200,15168.195000,4.740389,156719.75
2,Capital Federal,2012,3038860,1414105,1624755,2,1150134,1423973,1082998,200,15194.300000,4.748916,156719.75
3,Capital Federal,2013,3044076,1418339,1625737,2,1150134,1423973,1082998,200,15220.380000,4.757434,156719.75
4,Capital Federal,2014,3049229,1422507,1626722,2,1150134,1423973,1082998,200,15246.145000,4.765849,156719.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,Tierra del Fuego,2036,241593,122567,119026,94,38956,43360,36689,1002445,0.241004,-0.213774,156719.75
740,Tierra del Fuego,2037,245734,124625,121109,94,38956,43360,36689,1002445,0.245135,-0.213773,156719.75
741,Tierra del Fuego,2038,249853,126670,123183,94,38956,43360,36689,1002445,0.249244,-0.213771,156719.75
742,Tierra del Fuego,2039,253948,128702,125246,94,38956,43360,36689,1002445,0.253329,-0.213770,156719.75
743,Tierra del Fuego,2040,258020,130721,127299,94,38956,43360,36689,1002445,0.257391,-0.213769,156719.75

**INFORME REALIZADO SOBRE LOS DATOS DE LA VARIABLE SUPERFICIE EN KM2**

*   Se observa que Capital Federal está por fuera del valor de la media
*   Capital Federal tiene la menor superficie